project:
  type: website

website:
  title: "Kaitlynn Gray"
  sidebar:
    style: docked
    search: false
    pinned: true
    contents:
  #navbar:
    #left:
      - href: index.qmd
        text: Home
      - href: tab-code/index.qmd
        text: Code
      - href: tab-design/index.qmd
        text: Design
      - href: tab-research/index.qmd
        text: Research
      #- href: projects/
      #  text: Projects
      #- about.qmd

  page-footer:
    right: kaitlynn is cool

format:
  html:
    theme: styles-adv.scss
    mainfont: IBM Plex Mono
    #css: styles.css
    toc: false



