project:
  type: website

website:
  title: "Kaitlynn's Portfolio Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/
        text: Projects
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



