project:
  type: website

website:
  title: "Kaitlynn Gray"
  sidebar:
    style: docked
    search: false
    pinned: true
    contents:
  #navbar:
    #left:
      - href: index.qmd
        text: Home
      - href: tab-code/index.qmd
        text: Code
      - href: tab-design/index.qmd
        text: Design
      - href: tab-research/index.qmd
        text: Research
      - href: tab-art/index.qmd
        text: Art
      - href: tab-about-me/index.qmd
        text: About Me
      #- href: projects/
      #  text: Projects
      #- about.qmd

  # page-footer:
  #   left: 
  #     - href: mailto:kagray@g.hmc.edu
  #       text: kagray@g.hmc.edu

format:
  html:
    theme: styles-adv.scss
    mainfont: Lexend, Arial, sans-serif #IBM Plex Mono
    #css: styles.css
    toc: false



