:::::::::{.code-proj-body}

:::::::{.code-proj-top}

:::::{.code-proj-info}

:::{.code-proj-title}
MUSE
:::

:::{.code-proj-names}
Eshanya Agrawal, Deniz Bajin, Zariah Folkes, Kaitlynn Gray

:::

:::{.code-proj-class}
**Course:** Computational Design Tools

**Tools:** HTML, CSS, JavaScript

:::

:::{.code-proj-links}
[Paper](https://github.com/)

[Design Documentation](https://github.com/)

[GitHub Repository](https://github.com/)
:::



:::::

:::::{.code-proj-image}
heyy
:::::



:::::::

:::::::{.code-proj-bottom}



:::::{.code-proj-desc}

### Description
MUSE is a digital DJ board website. MUSE is a tool for people to better understand how different parts of sound relate to each other. This is to provide a foundation for those interested in producing music. We help visualize these different parts by associating sound with color.

So, instead of playing music tracks, users can play colors as sounds. Users can change the tint and saturation of the colors using sliders. These sliders also impact the sound of the color - changing tint changes the speed, and changing saturation changes the volume. This allows users to see the visual impacts of changing parts of sound. We hope that by connecting a visual change with altering sound, users can better understand how the speed and volume change a music track.

Users can play two colors at once to create a sound mixture and save them.

:::::


### Screenshots

:::::{.screenshots-container}

:::{.screenshot}
#### Welcome Page

this is the welcome page
:::

:::{.screenshot}
#### Main Page

this is the main page
:::

:::{.screenshot}
#### Saved Colors Page

this is the saved colors page
:::

:::{.screenshot}
#### Help Page

this is the help page
:::


:::::


:::::::

:::::::::